name       : sardi-icons
version    : '20.9'
release    : 14
source     :
    - https://netcologne.dl.sourceforge.net/project/sardi/sardi-icons-20.9-1.tar.gz : b1da636b9426aea47617d3f169664dbb3f0112a03b6ea15a594c41fea5971cc4
homepage   : https://erikdubois.be/
license    : CC-BY-NC-SA-4.0
component  :
    - desktop.theme
    - colora : desktop.theme
    - flat : desktop.theme
    - flexible : desktop.theme
    - ghost : desktop.theme
    - mono : desktop.theme
    - numix : desktop.theme
    - vertexed : desktop.theme
summary    : Simple and flat icon theme with long shadow
description: |
    Simple and flat icon theme with long shadow
patterns   :
    - colora : [/usr/share/icons/Sardi-Orb-Colora]
    - flat : [/usr/share/icons/*Flat*]
    - flexible : [/usr/share/icons/*Sardi-Flexible*]
    - ghost : [/usr/share/icons/*Ghost*]
    - mono : [/usr/share/icons/*Mono*]
    - numix : [/usr/share/icons/*Numix*]
    - vertexed : [/usr/share/icons/*Vertexed]
rundeps    :
    - colora : sardi-icons-flat
    - flat : sardi-icons
    - flexible : sardi-icons
    - ghost : sardi-icons
    - numix : sardi-icons-mono
    - mono : sardi-icons
    - vertexed : sardi-icons-mono
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -R * $installdir/usr/share/icons/

    # Clean unused icons
    pushd $installdir/usr/share/icons/
    for icons in Sardi Sardi-Orb-Colora Sardi-Flat Sardi-Flexible Sardi-Ghost-Flexible Sardi-Mono; do
        mv ${icons}/scalable/apps/web-browser.svg ${icons}/scalable/apps/wb.svg
        mv ${icons}/scalable/apps/distributor-logo.svg ${icons}/scalable/apps/d-logo.svg
        mv ${icons}/scalable/apps/distributor-logo-solus.svg ${icons}/scalable/apps/d-logo-solus.svg
        mv ${icons}/scalable/apps/xfce4-panel.svg ${icons}/scalable/apps/new-icon-panel.svg
        mv ${icons}/scalable/apps/xfce4-workspaces.svg ${icons}/scalable/apps/new-icon-workspaces.svg
        mv ${icons}/scalable/apps/xfce4-session.svg ${icons}/scalable/apps/new-icon-session.svg
        mv ${icons}/scalable/apps/xfce-sensors.svg ${icons}/scalable/apps/new-icon-sensors.svg
    done
    
    for del in *Amazon* *LICENSE* *changelog* *chrome-* *cinnamon-* *distributor-* *emerald-* *icon-theme.cache* \
        *lite* *masterpdf* *mintbackup* *mintdrivers* *mints* *mintup* *mintwhel* *mx-* *nero* *netflix* *nuvola* \
        *openofficeorg* *ooo-* *peppermint* *popcorntime* *redhat* *silicon* *unity-* *unity8-* *web-* *xf* \
        *amazon* *arco* *debian* *deepin* *facebook* *fedora* *google-play* *googleplay* *kingsoft* \
        *mageia* *mandriva* *manjaro* *lx* *sparkleshare* *ubuntu*; do
        find -path "${del}" -prune -exec rm -rv '{}' \;
    done
        
    for icons in Sardi Sardi-Orb-Colora Sardi-Flat Sardi-Flexible Sardi-Ghost-Flexible Sardi-Mono; do
        mv ${icons}/scalable/apps/wb.svg ${icons}/scalable/apps/web-browser.svg
        mv ${icons}/scalable/apps/d-logo.svg ${icons}/scalable/apps/distributor-logo.svg
        mv ${icons}/scalable/apps/d-logo-solus.svg ${icons}/scalable/apps/distributor-logo-solus.svg
        mv ${icons}/scalable/apps/new-icon-panel.svg ${icons}/scalable/apps/xfce4-panel.svg
        mv ${icons}/scalable/apps/new-icon-workspaces.svg ${icons}/scalable/apps/xfce4-workspaces.svg
        mv ${icons}/scalable/apps/new-icon-session.svg ${icons}/scalable/apps/xfce4-session.svg
        mv ${icons}/scalable/apps/new-icon-sensors.svg ${icons}/scalable/apps/xfce-sensors.svg
    done   
    popd
    
    # Remove broken symlinks, scripts and Mint version
    find $installdir/usr/share/icons/* -xtype l -delete
    rm -rf $installdir/usr/share/icons/*Mint*
    rm -fv $installdir/usr/share/icons/*/{Sardi*.sh,change*.sh}
