name       : sardi-icons
version    : '20.2_2'
release    : 11
source     :
    - https://netcologne.dl.sourceforge.net/project/sardi/sardi-icons-20.2-2.tar.gz : a9e8582fd9149ecfba739fd3244624bb59e2ec941f4c7de71b7fc431cfef9961
homepage   : https://erikdubois.be/
license    : CC-BY-NC-SA-4.0
component  : desktop.theme
summary    : Simple and flat icon theme with long shadow
description: |
    Simple and flat icon theme with long shadow
patterns   :
    - /usr/share/icons/Sardi
    - /usr/share/icons/*Arc
    - /usr/share/icons/"Sardi Flexible"*
    - /usr/share/icons/"Sardi Mono"
    - colora : [/usr/share/icons/*Colora*]
    - flat : [/usr/share/icons/*Flat*]
    - ghost : [/usr/share/icons/*Ghost*]
    - numix : [/usr/share/icons/*Numix*]
    - vertexed : [/usr/share/icons/*Vertexed]
rundeps    :
    - colora :
        - sardi-icons
    - flat :
        - sardi-icons-colora
    - ghost :
        - sardi-icons
    - numix :
        - numix-icon-theme
        - sardi-icons-colora
    - vertexed :
        - sardi-icons
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -R * $installdir/usr/share/icons/

    # Delete useless files, scripts and Mint version
    rm -rf $installdir/usr/share/icons/*Mint*
    rm -f $installdir/usr/share/icons/*/{LICENSE,Sardi*.sh,change-colo*.sh,changelog,create-new-icon-theme.cache.sh,icon-theme.cache}
