name       : sardi-icons
version    : 9.6.22
release    : 7
source     :
    - https://downloads.sourceforge.net/project/sardi/sardi-icons-9.6-22.tar.gz : fd5dc9d3c416f936542986cc703e18b3ae3c8c3f6596c0a0f4cbb9f5fa512b06
license    : GPL-2.0
component  : desktop.theme
summary    : Simple and flat icon theme with long shadow
description: |
    Simple and flat icon theme with long shadow
patterns   :
    - /usr/share/icons/Sardi
    - /usr/share/icons/*Arc
    - /usr/share/icons/"Sardi Flexible"*
    - /usr/share/icons/"Sardi Mono"
    - colora : [/usr/share/icons/*Colora*]
    - flat : [/usr/share/icons/*Flat*]
    - ghost : [/usr/share/icons/*Ghost*]
    - numix : [/usr/share/icons/*Numix*]
    - vertexed : [/usr/share/icons/*Vertexed]
rundeps    :
    - breeze :
        - breeze-icons
        - sardi-icons
    - colora :
        - sardi-icons
    - flat :
        - sardi-icons-colora
    - ghost :
        - sardi-icons
    - numix :
        - numix-icon-theme
        - sardi-icons-colora
    - vertexed :
        - sardi-icons
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -R * $installdir/usr/share/icons/
    rm -rf $installdir/usr/share/icons/*Archlabs*
    rm -rf $installdir/usr/share/icons/*Mint*
